version: '3'
services:
  postgres:
    env_file:
      - .env
    restart: always
    image: postgres:15.3
    ports:
      - 25432:5432
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASS
volumes:
  postgres-data:
